/** @format */

import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import StoreProvider from "./StoreProvider";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "@/utils/nextAuthProvider";

const inter = Inter({ subsets: ["latin"] });
const sourcecode = Source_Code_Pro({
   subsets: ["latin"],
   display: "swap",
   variable: "--font-code",
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}


export default function RootLayout({children}: Readonly<RootLayoutProps>) {
   return (
      <html lang="en">
        <NextAuthProvider>
            <StoreProvider>
               <ConfigProvider
                  theme={{
                     components: {
                        Button: {
                           defaultShadow: "none",
                        },
                     },
                  }}
               >
                  <body className={sourcecode.variable}>
                     <AntdRegistry>{children}</AntdRegistry>
                  </body>
               </ConfigProvider>
            </StoreProvider>
            </NextAuthProvider>
      </html>
   );
}
